social.kakao:
  client-id: e751159ca81bed9e63019fd186179e47
  client-secret: r9M8z9vXRF9N8C1Wlw1ALbuCVOW6izSp
  redirect: "/oauth"
  #"/login/oauth2/code/kakao"
  url.token: "https://kauth.kakao.com/oauth/token"
  url.profile: "https://kapi.kakao.com/v2/user/me"
spring:
  jwt:
    secret: SnNvbldlYlRva2VuQXV0aGVudGljYXRpb25XaXRoU3ByaW5nQm9vdFRlc3RQcm9qZWN0U2VjcmV0S2V5
