logging:
  level:
    root: warn
    com.restApi.restApiSpringBootApp: debug #debug info warn error fatal off
    org.hibernate.type: trace
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-database.cptu2czd8oqz.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: admin
    password: capstone
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      format_sql: true
    show-sql: true
    open-in-view: false
  url:
    base: http://localhost:8080
  config:
    activate:
      on-profile: local
  redis:
    host: 13.209.138.240
    port: 6379
