social.kakao:
  client-id: ${KAKAO_OAUTH_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECERET}
  redirect: "/oauth2/"
  url.token: "https://kauth.kakao.com/oauth/token"
  url.profile: "https://kapi.kakao.com/v2/user/me"
spring:
  jwt:
    secret: SnNvbldlYlRva2VuQXV0aGVudGljYXRpb25XaXRoU3ByaW5nQm9vdFRlc3RQcm9qZWN0U2VjcmV0S2V5
